sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  slack:
    secure: DioZVwYJgu9Ilwr8qckXvQRxukezd+B/xqs8cT4Tw0mFfE3IoJsIMYE8kxi9UdMrauqnf87JokY4H/pwwEwvNksfHKt7Pa3JdwOjRRTTIj1rI19uBd8UV0q1fcIGYcYEULz87ugZlAQOn+SU9EpETRUn/6DspNfZJkmGBrG5Rs8=
  email:
    recipients:
      secure: KhWz7JyaiwXS35I+BkzutWHI9dlIOoq97bmF/7Dd3ZKFFL05/mN/hirH+dZYWqsGECJKPzWBtbizk+RaPmrFBnWyidxLFG+3PS/RTgAYdBPxQ7RsbRspmx/gncCWZcSQhYToMQn7qXlCw+jLHi+oxXsymnkmyQ9/bwia8B3Khxg=
